http_options: 
  host: 0.0.0.0
  port: 7000
applications:
  - name: API
    import_path: api:app_builder
    deployments:
    - name: API
      num_replicas: 1
      ray_actor_options:
        num_gpus: 1
    args:
      llms:
        completions:
          - name: "../models/vicuna-7b/"
            class: "vicuna"
          # - name: ""
          #   class: "llama2"
          # - name: ""
          #   class: "llama.cpp"
        embedding:
          # - name: "hkunlp/instructor-large"
          #   class: "instructor"
          - name: "sentence-transformers/all-MiniLM-L12-v2"
            class: "sentence-transformers"
          - name: "sentence-transformers/all-MiniLM-L6-v2"
            class: "sentence-transformers"